INSERT INTO student (name, groupnumber) VALUES ('John', 1);
INSERT INTO student (name, groupnumber) VALUES ('Chris', 1);
INSERT INTO student (name, groupnumber) VALUES ('Carl', 1);
INSERT INTO student (name, groupnumber) VALUES ('Oliver', 2);
INSERT INTO student (name, groupnumber) VALUES ('James', 2);
INSERT INTO student (name, groupnumber) VALUES ('Lucas', 2);
INSERT INTO student (name, groupnumber) VALUES ('Henry', 2);
INSERT INTO student (name, groupnumber) VALUES ('Jacob', 3);
INSERT INTO student (name, groupnumber) VALUES ('Logan', 3);
INSERT INTO student (name, groupnumber) VALUES ('Anvar', 4);
INSERT INTO student (name, groupnumber) VALUES ('Qobil', 4);
INSERT INTO student (name, groupnumber) VALUES ('Dilshod', 4);
INSERT INTO student (name, groupnumber) VALUES ('Akram', 5);
INSERT INTO student (name, groupnumber) VALUES ('Sardor', 5);
INSERT INTO student (name, groupnumber) VALUES ('Komil', 5);
INSERT INTO subject (name, grade) VALUES ('Art', 1);
INSERT INTO subject (name, grade) VALUES ('Music', 1);
INSERT INTO subject (name, grade) VALUES ('Geography', 2);
INSERT INTO subject (name, grade) VALUES ('History', 2);
INSERT INTO subject (name, grade) VALUES ('PE', 3);
INSERT INTO subject (name, grade) VALUES ('Math', 3);
INSERT INTO subject (name, grade) VALUES ('Science', 4);
INSERT INTO subject (name, grade) VALUES ('IT', 4);
INSERT INTO subject (name, grade) VALUES ('Geography', 5);
INSERT INTO subject (name, grade) VALUES ('Science', 5);
INSERT INTO paymenttype (name) VALUES ('DAILY'), ('WEEKLY'), ('MONTHLY');
INSERT INTO payment (type_id, student_id) VALUES (SELECT id from paymenttype where name = 'WEEKLY', SELECT id from student where name = 'John'), (SELECT id from paymenttype where name = 'MONTHLY', SELECT id from student where name = 'Oliver'), (SELECT id from paymenttype where name = 'WEEKLY', SELECT id from student where name = 'Henry'), (SELECT id from paymenttype where name = 'DAILY', SELECT id from student where name = 'James');
INSERT INTO mark (subject_id, student_id, mark) VALUES (SELECT id from subject where name = 'Art', SELECT id from student where name = 'Chris', 8), (SELECT id from subject where name = 'History', SELECT id from student where name = 'Oliver', 5), (SELECT id from subject where name = 'Geography', SELECT id from student where name = 'James', 9), (SELECT id from subject where name = 'Math', SELECT id from student where name = 'Jacob', 4), (SELECT id from subject where name = 'PE', SELECT id from student where name = 'Logan', 9);